export const INFO_STATIC = {
  name: 'Papelera Pepito',
  description: 'Generated by create next app',
  keywords: 'library, online, e-commerce',
  address: 'calle falsa 123',
  links: {
    instagram: 'https://www.instagram.com/',
  },
  lang: 'sp',
} as const;
