export const TypesCompose = {
  userCtrl: Symbol.for('userController'),
  userRepo: Symbol.for('userRepository'),
  productCtrl: Symbol.for('productController'),
  productRepo: Symbol.for('productRepository'),
  productClientCtrl: Symbol.for('productClientController'),
  productClientRepo: Symbol.for('productClientRepository'),
  markCtrl: Symbol.for('markController'),
  markRepo: Symbol.for('markRepository'),
  orderCtrl: Symbol.for('orderController'),
  orderRepo: Symbol.for('orderRepository'),
  categoryCtrl: Symbol.for('categoryController'),
  categoryRepo: Symbol.for('categoryRepository'),
  tagCtrl: Symbol.for('tagController'),
  tagRepo: Symbol.for('tagRepository'),
};
